### ISSUE TITLE
IllegalStateException when using scenario executor for integration tests

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie-vert.x#25]
java.lang.IllegalStateException: Client is closed
	at io.vertx.core.net.impl.NetClientImpl.checkClosed(NetClientImpl.java:186)
	at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:230)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$5(NetClientImpl.java:267)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Tyagi-Gaurav** [comment]
Changed tests to use Spring WebTest client, so not having this issue anymore. Plus, this has made the tests more deterministic.
